version: '3.3'

services:

  amq:
    image: apache/artemis-adoptopenjdk-11:2.22.0
    container_name: activemq
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
    ports:
      - "8161:8161"
      - "61616:61616"